### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by frankopkusianwar** [frankopkusianwar/Animal-Care-REACT#2]
Any feedback is much appreciated

**Comment by kubilaycaglayan** [comment]
Hello Frank :wave: Thanks for the presentation! You can give e feedback to the users if the content is not loading after a certain time. So the users will not wait for the "loading..." screen. :blush:

**Comment by teekaytech** [comment]
Thank you for the presentation, Frank.

**Comment by mariosknl** [comment]
Great presentation Frank. You have a great job with this project. My recommendation though is to check a package called 'redux-toolkit'. It will make your code even cleaner and less at the same time.
